

export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_PRODUCT_ALL = "GET_PRODUCT_ALL";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const GET_SEARCHED_PRODUCT = "GET_SEARCHED_PRODUCT";

